# SCREEN CONSTANTS
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

# ASTEROID CONSTANTS
ASTEROID_MIN_RADIUS = 30
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = .6  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# PLAYER CONSTANTS
PLAYER_RADIUS = 25
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 250
ROTATION_SPEED = 4
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_CD = 1

# LIVES OR HEALTH
# LIVES = 3
# HEALTH = 100

# SHOT CONSTANTS
SHOT_RADIUS = 5
SHOT_RADIUS2 = 10
SHOT_RADIUS3 = 2

