# SCREEN CONSTANTS
SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 800

# ASTEROID CONSTANTS
ASTEROID_MIN_RADIUS = 15
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = .5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# PLAYER CONSTANTS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 80
ROTATION_SPEED = 4
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_CD = 0

# LIVES OR HEALTH
# LIVES = 3
# HEALTH = 100

# SHOT CONSTANTS
SHOT_RADIUS = 5
SHOT_RADIUS2 = 10
SHOT_RADIUS3 = 2

